### ISSUE TITLE
Youtube statt spotify-link

### ISSUE THREAD

**Issue by Krisselack** [Pacerino/pr0sauce_userscript#1]
Wäre es möglich, statt spotify einen YouTube link zu erhalten? Ansonsten, sehr cooles Programm, danke!

**Comment by Pacerino** [comment]
Das Userscript setzt den Link zur Website, sofern zu dem Titel ein YouTube Link vorhanden ist, wird dieser auch dort angezeigt. Da nicht viele Songs einen YouTube Link besitzen, fehlt dieser häufig. Spotify dagegen ist zu 95% vorhanden. Das einzige was du machen kannst, ist den Titel und den Artisten auf YouTube zu suche. Ich werd dafür einfach einen Direktlink auf die Website packen.
